### ISSUE TITLE
Removing o-w perms removes group bit as well

### ISSUE THREAD

**Issue by ology** [xenoterracide/File-chmod#5]
Via system calls, all is well:

> ls -l foo
> -rwxrwxrwx  1 gboggs  staff  0 Feb 13 13:38 foo
> chmod o-w foo
> ls -l foo
> -rwxrwxr-x  1 gboggs  staff  0 Feb 13 13:38 foo

But with File::chmod, the group write bit is also removed for the same command:

> ls -l foo
> -rwxrwxrwx  1 gboggs  staff  0 Feb 13 13:38 foo
> perl -MFile::chmod -e'chmod "o-w", shift' foo
> ls -l foo
> -rwxr-xr-x  1 gboggs  staff  0 Feb 13 13:38 foo

**Comment by xenoterracide** [comment]
`perl -MFile::chmod -e'$File::chmod::UMASK = 0; chmod "o-w", shift' test`

**Comment by xenoterracide** [comment]
somehow I had though I'd find having umask set, and system chmod obeying it... I'm not sure how I encountered that, but even if I derevert the deprecation there isn't a great way to proceed, and I'd have to sit on it for at least a year considering the age of the library and how long that behavior existed.

**Comment by ology** [comment]
Whoops.  Guess I should have better RTFM'd. :-/

> ...It's also fairly loudly documented.

**Comment by xenoterracide** [comment]
don't worry about it, it was a reminder to me that I need to kill this insane default behavior given enough time. eventually I, or someone, should look into an API where these aren't set at the package level
